In [1]:
import polars as pl

In [2]:
filepath = "../data_source/online_retail_II.csv"

In [3]:
try:
    df = pl.read_csv(filepath, schema_overrides={"Invoice": pl.String})
except Exception as e:
    print(e)

In [4]:
df.head()

shape: (5, 8)
┌─────────┬───────────┬───────────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description       ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---               ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ str     ┆ str       ┆ str               ┆ i64      ┆ str         ┆ f64   ┆ f64         ┆ str     │
╞═════════╪═══════════╪═══════════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 489434  ┆ 85048     ┆ 15CM CHRISTMAS    ┆ 12       ┆ 2009-12-01  ┆ 6.95  ┆ 13085.0     ┆ United  │
│         ┆           ┆ GLASS BALL 20 L…  ┆          ┆ 07:45:00    ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 79323P    ┆ PINK CHERRY       ┆ 12       ┆ 2009-12-01  ┆ 6.75  ┆ 13085.0     ┆ United  │
│         ┆           ┆ LIGHTS            ┆          ┆ 07:45:00    ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 79323W    ┆ WHITE CHERRY      ┆ 12       ┆ 2009-12-01  ┆ 6.75  ┆ 13085.0     ┆ United  │
│         ┆           ┆ LIGHTS            ┆          ┆ 07:45:00    ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 22041     ┆ RECORD FRAME 7"   ┆ 48       ┆ 2009-12-01  ┆ 2.1   ┆ 13085.0     ┆ United  │
│         ┆           ┆ SINGLE SIZE       ┆          ┆ 07:45:00    ┆       ┆             ┆ Kingdom │
│ 489434  ┆ 21232     ┆ STRAWBERRY        ┆ 24       ┆ 2009-12-01  ┆ 1.25  ┆ 13085.0     ┆ United  │
│         ┆           ┆ CERAMIC TRINKET   ┆          ┆ 07:45:00    ┆       ┆             ┆ Kingdom │
│         ┆           ┆ BOX               ┆          ┆             ┆       ┆             ┆         │
└─────────┴───────────┴───────────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [5]:
df.glimpse()

Rows: 1067371
Columns: 8
$ Invoice     <str> '489434', '489434', '489434', '489434', '489434', '489434', '489434', '489434', '489435', '489435'
$ StockCode   <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity    <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <str> '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:45:00', '2009-12-01 07:46:00', '2009-12-01 07:46:00'
$ Price       <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID <f64> 13085.0, 13085.0, 13085.0, 13085.0, 13085.0, 13085.0, 13085.0, 13085.0, 13085.0, 13085.0
$ Country     <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [6]:
df.describe()

shape: (9, 9)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ Invoice ┆ StockCode ┆ Descripti ┆ … ┆ InvoiceDa ┆ Price     ┆ Customer  ┆ Country   │
│ ---        ┆ ---     ┆ ---       ┆ on        ┆   ┆ te        ┆ ---       ┆ ID        ┆ ---       │
│ str        ┆ str     ┆ str       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ str       │
│            ┆         ┆           ┆ str       ┆   ┆ str       ┆           ┆ f64       ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 1067371 ┆ 1067371   ┆ 1062989   ┆ … ┆ 1067371   ┆ 1.067371e ┆ 824364.0  ┆ 1067371   │
│            ┆         ┆           ┆           ┆   ┆           ┆ 6         ┆           ┆           │
│ null_count ┆ 0       ┆ 0         ┆ 4382      ┆ … ┆ 0         ┆ 0.0       ┆ 243007.0  ┆ 0         │
│ mean       ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ 4.649388  ┆ 15324.638 ┆ null      │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆           │
│ std        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ 123.55305 ┆ 1697.4644 ┆ null      │
│            ┆         ┆           ┆           ┆   ┆           ┆ 9         ┆ 5         ┆           │
│ min        ┆ 489434  ┆ 10002     ┆ DOORMAT   ┆ … ┆ 2009-12-0 ┆ -53594.36 ┆ 12346.0   ┆ Australia │
│            ┆         ┆           ┆ UNION     ┆   ┆ 1         ┆           ┆           ┆           │
│            ┆         ┆           ┆ JACK GUNS ┆   ┆ 07:45:00  ┆           ┆           ┆           │
│            ┆         ┆           ┆ AND …     ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ 1.25      ┆ 13975.0   ┆ null      │
│ 50%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ 2.1       ┆ 15255.0   ┆ null      │
│ 75%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ 4.15      ┆ 16797.0   ┆ null      │
│ max        ┆ C581569 ┆ m         ┆ wrongly   ┆ … ┆ 2011-12-0 ┆ 38970.0   ┆ 18287.0   ┆ West      │
│            ┆         ┆           ┆ sold sets ┆   ┆ 9         ┆           ┆           ┆ Indies    │
│            ┆         ┆           ┆           ┆   ┆ 12:50:00  ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
print(df.shape)

(1067371, 8)

In [8]:
unique_list = df["Description"].unique().to_list()
len(unique_list)

5699